# ELK
version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.3
    container_name: elasticsearch
    volumes:
      - $PWD/conf-files/es-conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:4.5
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
  logstash:
    image: logstash:2.3
    container_name: logstash
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - $PWD/conf-files/logstash-conf:/opt/logstash/conf.d
    command: -f /opt/logstash/conf.d/logstash.conf

volumes:
  elasticsearch-data:
