# ELK
version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - $PWD/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:4.5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
  logstash:
    build: ./logstash
    ports:
      - "9991:9991"
      - "9991:9991/udp"
      - "9997:9997"
    volumes:
      - $PWD/sources:/etc/logstash/conf.d
      - $PWD/sources/syslog/patterns:/etc/logstash/patterns
    command: -f /etc/logstash/conf.d/*/*.conf
    depends_on:
      - rabbitmq
      - pmacct
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  pmacct:
    build: ./pmacct
    ports:
      - "23501:23501/udp"
      - "23502:23502/udp"
    depends_on:
      - rabbitmq
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data

volumes:
  elasticsearch-data:
  redis-data:
