# ELK
version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - $PWD/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:4.5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
  logstash:
    build: ./logstash
    image: logstash:2.3
    ports:
      - "9991:9991"
      - "9991:9991/udp"
    volumes:
      - $PWD/sources/syslog:/etc/logstash/conf.d/syslog
      - $PWD/sources/syslog/patterns:/etc/logstash/patterns
    command: -f /etc/logstash/conf.d/*/*.conf

volumes:
  elasticsearch-data:
