# ELK
version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - $PWD/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:4.5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
  logstash:
    image: logstash:2.3
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - $PWD/config/logstash:/opt/logstash/conf.d
    command: -f /opt/logstash/conf.d/logstash.conf

volumes:
  elasticsearch-data:
